"""constants package – re-exports all constant data."""
from .nbc105_2025_data import (
    ZONE_FACTOR_DATA, IMPORTANCE_FACTORS, SOIL_PARAMS,
    KT_VALUES, PERIOD_AMPLIFICATION_FACTOR, ACCIDENTAL_ECCENTRICITY,
    DEFLECTION_SCALE_FACTORS_KD, SEISMIC_LIVE_LOAD_FACTORS, KTM_VALLEY_SOIL_D,
)
from .structural_systems import STRUCTURAL_SYSTEMS, DEFLECTION_AMPLIFICATION
from .is456_data import (
    SLAB_MOMENT_COEFFICIENTS, SHEAR_STRENGTH_CONCRETE,
    DEFLECTION_KT_DATA, BEAM_MOMENT_COEFFICIENTS,
)
from .load_data import LIVE_LOAD_DATA

__all__ = [
    "ZONE_FACTOR_DATA", "IMPORTANCE_FACTORS", "SOIL_PARAMS",
    "KT_VALUES", "PERIOD_AMPLIFICATION_FACTOR", "ACCIDENTAL_ECCENTRICITY",
    "DEFLECTION_SCALE_FACTORS_KD", "SEISMIC_LIVE_LOAD_FACTORS", "KTM_VALLEY_SOIL_D",
    "STRUCTURAL_SYSTEMS", "DEFLECTION_AMPLIFICATION",
    "SLAB_MOMENT_COEFFICIENTS", "SHEAR_STRENGTH_CONCRETE",
    "DEFLECTION_KT_DATA", "BEAM_MOMENT_COEFFICIENTS",
    "LIVE_LOAD_DATA", "APP_NAME", "APP_VERSION",
]

APP_NAME = "Structural Calculator"
APP_VERSION = "v1.0.0"
