"""
constants/nbc105_2025_data.py
──────────────────────────────
All seismic-hazard data mandated by NBC 105:2025 (Second Revision).

Key changes vs NBC 105:2020
────────────────────────────
* K (shear-stiffness) parameter REMOVED from soil table (Table 4-1).
* Spectral shape factor formula updated: velocity-sensitive plateau between
  Tc and Td uses  Ch(T) = α·Tc / T  (not the old K-based expression).
* Kt for Eccentrically Braced Steel Frame corrected to 0.075 (was 0.085).
* Kt for Moment Resisting STEEL Frame is now explicitly 0.085.
* Approximate period T1 = kt · H^(3/4) must be multiplied by 1.25 (§ 5.1.3).
* Accidental eccentricity reduced to ±0.05b.
* Soil Type D no longer defined by municipality name; now defined by Vs,30
  (Table 4-2). Kathmandu-valley ward-level table still provided for defaults.
* Deflection scale factors kd added (Table 6-1).
* Cs(T) = 0.20 · C(T)  (unchanged from 2020).
* Zone factors updated from Annex C Table C-1 (2025 revision) — 751 local units.
"""

# ── Zone Factors (Z) ──────────────────────────────────────────────────────────
# PGA for 475-year return period, from Annex C / Table C-1 (2025 revision)
# Keys are local unit names; duplicates across districts use "District, Name"
ZONE_FACTOR_DATA: dict[str, float] = {
    "Aamchowk Gaunpalika": 0.4,
    "Aandhikhola Gaunpalika": 0.35,
    "Aarughat Gaunpalika": 0.3,
    "Aathabis Nagarpalika": 0.35,
    "Aathbiskot Nagarpalika": 0.3,
    "Aathrai Gaunpalika": 0.35,
    "Aathrai Tribeni Gaunpalika": 0.35,
    "Aaurahi Gaunpalika": 0.35,
    "Adanchuli Gaunpalika": 0.3,
    "Adarshkotwal Gaunpalika": 0.35,
    "Adharsha Gaunpalika": 0.35,
    "Agnisair Krishna Savaran Gaunpalika": 0.35,
    "Ainselukhark Gaunpalika": 0.35,
    "Ajaymeru Gaunpalika": 0.35,
    "Ajirkot Gaunpalika": 0.3,
    "Alital Gaunpalika": 0.35,
    "Amargadhi Nagarpalika": 0.35,
    "Anbukhaireni Gaunpalika": 0.35,
    "Apihimal Gaunpalika": 0.3,
    "Arjunchaupari Gaunpalika": 0.35,
    "Arjundhara Nagarpalika": 0.35,
    "Arnama Gaunpalika": 0.35,
    "Arun Gaunpalika": 0.35,
    "Aurahi Gaunpalika": 0.35,
    "Aurahi Nagarpalika": 0.35,
    "Ayirabati Gaunpalika": 0.35,
    "Babai Gaunpalika": 0.4,
    "Badhaiyatal Gaunpalika": 0.35,
    "Badigad Gaunpalika": 0.35,
    "Badikedar Gaunpalika": 0.35,
    "Badimalika Nagarpalika": 0.35,
    "Bagchaur Nagarpalika": 0.35,
    "Baglung Nagarpalika": 0.35,
    "Bagmati Nagarpalika": 0.35,
    "Bagnaskali Gaunpalika": 0.35,
    "Bahudaramai Nagarpalika": 0.35,
    "Baijanath Gaunpalika": 0.4,
    "Baiteshwor Gaunpalika": 0.3,
    "Bakaiya Gaunpalika": 0.35,
    "Balan Bihul Gaunpalika": 0.35,
    "Balara Nagarpalika": 0.3,
    "Balefi Gaunpalika": 0.35,
    "Balwa Nagarpalika": 0.35,
    "Bandipur Gaunpalika": 0.35,
    "Banepa Nagarpalika": 0.35,
    "Banfikot Gaunpalika": 0.3,
    "Bangad Kupinde Nagarpalika": 0.35,
    "Banganga Nagarpalika": 0.35,
    "Banglachuli Gaunpalika": 0.4,
    "Bannigadhi Jayagadh Gaunpalika": 0.35,
    "Bansagadhi Nagarpalika": 0.4,
    "Baragadhi Gaunpalika": 0.35,
    "Barah Nagarpalika": 0.4,
    "Barahapokhari Gaunpalika": 0.4,
    "Barahathawa Nagarpalika": 0.35,
    "Barahtal Gaunpalika": 0.35,
    "Barbardiya Nagarpalika": 0.35,
    "Bardaghat Nagarpalika": 0.35,
    "Bardagoriya Gaunpalika": 0.35,
    "Bardibas Nagarpalika": 0.35,
    "Barekot Gaunpalika": 0.3,
    "Bareng Gaunpalika": 0.35,
    "Barhabise Nagarpalika": 0.3,
    "Barhadashi Gaunpalika": 0.35,
    "Barhagaun Muktikhsetra Gaunpalika": 0.3,
    "Bariyarpatti Gaunpalika": 0.35,
    "Barju Gaunpalika": 0.35,
    "Basbariya Gaunpalika": 0.35,
    "Bateshwor Gaunpalika": 0.35,
    "Baudhimai Nagarpalika": 0.3,
    "Bedkot Nagarpalika": 0.35,
    "Belaka Nagarpalika": 0.4,
    "Belauri Nagarpalika": 0.3,
    "Belbari Nagarpalika": 0.35,
    "Beldandi Gaunpalika": 0.35,
    "Belhi Chapena Gaunpalika": 0.35,
    "Belkotgadhi Nagarpalika": 0.35,
    "Beni Nagarpalika": 0.3,
    "Benighat Rorang Gaunpalika": 0.35,
    "Besishahar Nagarpalika": 0.3,
    "Bethanchowk Gaunpalika": 0.35,
    "Bhadrapur Nagarpalika": 0.35,
    "Bhagawanpur Gaunpalika": 0.35,
    "Bhagawatimai Gaunpalika": 0.35,
    "Bhageshwar Gaunpalika": 0.35,
    "Bhairabi Gaunpalika": 0.35,
    "Bhajani Nagarpalika": 0.35,
    "Bhaktapur Nagarpalika": 0.35,
    "Bhangaha Nagarpalika": 0.35,
    "Bhanu Nagarpalika": 0.35,
    "Bharatpur Mahanagarpalika": 0.4,
    "Bheri Nagarpalika": 0.35,
    "Bheriganga Nagarpalika": 0.4,
    "Bhimad Nagarpalika": 0.35,
    "Bhimdatta Nagarpalika": 0.35,
    "Bhimeshwor Nagarpalika": 0.3,
    "Bhimphedi Gaunpalika": 0.35,
    "Bhimsen Gaunpalika": 0.35,
    "Bhirkot Nagarpalika": 0.35,
    "Bhojpur Nagarpalika": 0.35,
    "Bhokraha Narsingh Gaunpalika": 0.35,
    "Bhotekoshi Gaunpalika": 0.3,
    "Bhotkhola Gaunpalika": 0.3,
    "Bhume Gaunpalika": 0.3,
    "Bhumekasthan Nagarpalika": 0.35,
    "Bhumlu Gaunpalika": 0.35,
    "Bideha Nagarpalika": 0.35,
    "Bidur Nagarpalika": 0.35,
    "Bigu Gaunpalika": 0.3,
    "Bihadi Gaunpalika": 0.35,
    "Bijayanagar Gaunpalika": 0.4,
    "Binayee Tribeni Gaunpalika": 0.35,
    "Bindabasini Gaunpalika": 0.35,
    "Biratnagar Mahanagarpalika": 0.35,
    "Birendranagar Nagarpalika": 0.4,
    "Birgunj Mahanagarpalika": 0.35,
    "Birtamod Nagarpalika": 0.35,
    "Biruwa Gaunpalika": 0.35,
    "Bishnu Gaunpalika": 0.3,
    "Bishrampur Gaunpalika": 0.35,
    "Bithadchir Gaunpalika": 0.35,
    "Bode Barsain Nagarpalika": 0.35,
    "Bogtan Gaunpalika": 0.35,
    "Bramhapuri Gaunpalika": 0.35,
    "Brindaban Nagarpalika": 0.35,
    "Buddhabhumi Nagarpalika": 0.4,
    "Buddhashanti Gaunpalika": 0.35,
    "Budhanilakantha Nagarpalika": 0.35,
    "Budhiganga Gaunpalika": 0.35,
    "Budhiganga Nagarpalika": 0.35,
    "Budhinanda Nagarpalika": 0.3,
    "Bulingtar Gaunpalika": 0.35,
    "Bungal Nagarpalika": 0.35,
    "Bungdikali Gaunpalika": 0.35,
    "Butwal Upamahanagarpalika": 0.35,
    "Byas Gaunpalika": 0.3,
    "Byas Nagarpalika": 0.35,
    "Chabispathivera Gaunpalika": 0.35,
    "Chainpur Nagarpalika": 0.35,
    "Chakraghatta Gaunpalika": 0.35,
    "Chame Gaunpalika": 0.3,
    "Champadevi Gaunpalika": 0.35,
    "Chamunda Bindrasaini Nagarpalika": 0.35,
    "Chandannath Nagarpalika": 0.3,
    "Chandragiri Nagarpalika": 0.35,
    "Chandrakot Gaunpalika": 0.35,
    "Chandranagar Gaunpalika": 0.35,
    "Chandrapur Nagarpalika": 0.35,
    "Changunarayan Nagarpalika": 0.35,
    "Chankheli Gaunpalika": 0.3,
    "Chapakot Nagarpalika": 0.35,
    "Chatrakot Gaunpalika": 0.35,
    "Chaubise Gaunpalika": 0.35,
    "Chaudandigadhi Nagarpalika": 0.4,
    "Chaukune Gaunpalika": 0.35,
    "Chaurideurali Gaunpalika": 0.35,
    "Chaurjahari Nagarpalika": 0.35,
    "Chaurpati Gaunpalika": 0.35,
    "Chautara SangachokGadhi Nagarpalika": 0.35,
    "Chharka Tangsong Gaunpalika": 0.3,
    "Chhathar Gaunpalika": 0.35,
    "Chhathar Jorpati Gaunpalika": 0.35,
    "Chhatradev Gaunpalika": 0.35,
    "Chhatreshwori Gaunpalika": 0.35,
    "Chhayanath Rara Nagarpalika": 0.3,
    "Chhedagad Nagarpalika": 0.35,
    "Chhededaha Gaunpalika": 0.35,
    "Chhinnamasta Gaunpalika": 0.35,
    "Chhipaharmai Gaunpalika": 0.35,
    "Chhireshwornath Nagarpalika": 0.35,
    "Chichila Gaunpalika": 0.3,
    "Chingad Gaunpalika": 0.35,
    "Chisankhugadhi Gaunpalika": 0.35,
    "Chitawan, Madi Nagarpalika": 0.4,
    "Chulachuli Gaunpalika": 0.35,
    "Chum Nubri Gaunpalika": 0.3,
    "Chure Gaunpalika": 0.35,
    "Dakneshwori Nagarpalika": 0.35,
    "Dakshinkali Nagarpalika": 0.35,
    "Dalome Gaunpalika": 0.3,
    "Damak Nagarpalika": 0.35,
    "Dangisharan Gaunpalika": 0.4,
    "Darchula, Mahakali Nagarpalika": 0.35,
    "Darma Gaunpalika": 0.35,
    "Dasharathchanda Nagarpalika": 0.35,
    "Deumai Nagarpalika": 0.4,
    "Devchuli Nagarpalika": 0.35,
    "Devdaha Nagarpalika": 0.35,
    "Devghat Gaunpalika": 0.35,
    "Devtal Gaunpalika": 0.35,
    "Dewahhi Gonahi Nagarpalika": 0.35,
    "Dewanganj Gaunpalika": 0.35,
    "Dhakari Gaunpalika": 0.35,
    "Dhanauji Gaunpalika": 0.35,
    "Dhangadhi Upamahanagarpalika": 0.4,
    "Dhangadhimai Nagarpalika": 0.4,
    "Dhankaul Gaunpalika": 0.35,
    "Dhankuta Nagarpalika": 0.4,
    "Dhankuta, Mahalaxmi Nagarpalika": 0.35,
    "Dhanpalthan Gaunpalika": 0.3,
    "Dhanusadham Nagarpalika": 0.35,
    "Dharche Gaunpalika": 0.3,
    "Dharmadevi Nagarpalika": 0.35,
    "Dhaulagiri Gaunpalika": 0.3,
    "Dhobini Gaunpalika": 0.35,
    "Dhorchaur Gaunpalika": 0.35,
    "Dhorpatan Nagarpalika": 0.35,
    "Dhulikhel Nagarpalika": 0.35,
    "Dhunibesi Nagarpalika": 0.35,
    "Dhurkot Gaunpalika": 0.35,
    "Dilasaini Gaunpalika": 0.35,
    "Dipayal Silgadi Nagarpalika": 0.35,
    "Diprung Gaunpalika": 0.35,
    "Dogadakedar Gaunpalika": 0.35,
    "Dolpo Buddha Gaunpalika": 0.25,
    "Doramba Gaunpalika": 0.35,
    "Dordi Gaunpalika": 0.3,
    "Dudhkoshi Gaunpalika": 0.3,
    "Dudhouli Nagarpalika": 0.35,
    "Dudhpokhari Gaunpalika": 0.3,
    "Duduwa Gaunpalika": 0.4,
    "Duhabi Nagarpalika": 0.35,
    "Duikholi Gaunpalika": 0.35,
    "Dullu Nagarpalika": 0.35,
    "Dungeshwor Gaunpalika": 0.35,
    "Dunhu Gaunpalika": 0.3,
    "Dupcheshwar Gaunpalika": 0.35,
    "Durga Bhagwati Gaunpalika": 0.3,
    "Durgathali Gaunpalika": 0.35,
    "Ekdanra Gaunpalika": 0.3,
    "Fakphokthum Gaunpalika": 0.35,
    "Falelung Gaunpalika": 0.35,
    "Falgunanda Gaunpalika": 0.35,
    "Gadhawa Gaunpalika": 0.4,
    "Gadhi Gaunpalika": 0.35,
    "Gadhimai Nagarpalika": 0.35,
    "Gaidahawa Gaunpalika": 0.35,
    "Gaidakot Nagarpalika": 0.35,
    "Gajuri Gaunpalika": 0.35,
    "Galchi Gaunpalika": 0.35,
    "Galkot Nagarpalika": 0.35,
    "Galyang Nagarpalika": 0.35,
    "Ganayapdhura Gaunpalika": 0.35,
    "Gandaki Gaunpalika": 0.35,
    "Ganeshman Charnath Nagarpalika": 0.35,
    "Gangajamuna Gaunpalika": 0.3,
    "Garuda Nagarpalika": 0.35,
    "Gaumukhi Gaunpalika": 0.35,
    "Gaumul Gaunpalika": 0.35,
    "Gaur Nagarpalika": 0.3,
    "Gauradhaha Nagarpalika": 0.35,
    "Gauriganga Nagarpalika": 0.35,
    "Gauriganj Gaunpalika": 0.3,
    "Gaurishankar Gaunpalika": 0.3,
    "Gaushala Nagarpalika": 0.35,
    "Geruwa Gaunpalika": 0.35,
    "Ghanglekh Gaunpalika": 0.35,
    "Gharapjhong Gaunpalika": 0.3,
    "Ghiring Gaunpalika": 0.35,
    "Ghodaghodi Nagarpalika": 0.35,
    "Ghorahi Upamahanagarpalika": 0.4,
    "Godaita Nagarpalika": 0.3,
    "Gokarneshwor Nagarpalika": 0.35,
    "Gokulganga Gaunpalika": 0.35,
    "Golanjor Gaunpalika": 0.35,
    "Golbazar Nagarpalika": 0.4,
    "Gorkha Nagarpalika": 0.35,
    "Gosaikunda Gaunpalika": 0.3,
    "Gramthan Gaunpalika": 0.35,
    "Gujara Nagarpalika": 0.35,
    "Gulariya Nagarpalika": 0.4,
    "Gulmi, Malika Gaunpalika": 0.35,
    "Gulmi, Musikot Nagarpalika": 0.35,
    "Gulmidarbar Gaunpalika": 0.35,
    "Gurans Gaunpalika": 0.35,
    "Gurbhakot Nagarpalika": 0.4,
    "Guthichaur Gaunpalika": 0.3,
    "Haldibari Gaunpalika": 0.35,
    "Halesi Tuwachung Nagarpalika": 0.35,
    "Hansapur Nagarpalika": 0.35,
    "Hanumannagar Kankalini Nagarpalika": 0.35,
    "Hariharpurgadhi Gaunpalika": 0.35,
    "Harinagar Gaunpalika": 0.35,
    "Harinas Gaunpalika": 0.35,
    "Haripur Nagarpalika": 0.35,
    "Haripurwa Nagarpalika": 0.35,
    "Hariwan Nagarpalika": 0.35,
    "Hatuwagadhi Gaunpalika": 0.4,
    "Helambu Gaunpalika": 0.3,
    "Hetauda Upamahanagarpalika": 0.4,
    "Hilihang Gaunpalika": 0.35,
    "Hima Gaunpalika": 0.3,
    "Himali Gaunpalika": 0.3,
    "Hupsekot Gaunpalika": 0.35,
    "Ichchhyakamana Gaunpalika": 0.35,
    "Illam Nagarpalika": 0.4,
    "Inaruwa Nagarpalika": 0.35,
    "Indrasarowar Gaunpalika": 0.35,
    "Indrawati Gaunpalika": 0.35,
    "Ishanath Nagarpalika": 0.3,
    "Ishworpur Nagarpalika": 0.35,
    "Isma Gaunpalika": 0.35,
    "Itahari Upamahanagarpalika": 0.35,
    "Jagadulla Gaunpalika": 0.3,
    "Jagarnathpur Gaunpalika": 0.35,
    "Jahada Gaunpalika": 0.3,
    "Jaimuni Nagarpalika": 0.35,
    "Jaleswor Nagarpalika": 0.3,
    "Jaljala Gaunpalika": 0.3,
    "Janaki Gaunpalika": 0.35,
    "Janaknandani Gaunpalika": 0.35,
    "Janakpur Upamahanagarpalika": 0.35,
    "Janki Gaunpalika": 0.4,
    "Jantedhunga Gaunpalika": 0.4,
    "JayaPrithivi Nagarpalika": 0.35,
    "Jhapa Gaunpalika": 0.3,
    "Jhimruk Gaunpalika": 0.35,
    "Jirabhawani Gaunpalika": 0.35,
    "Jiri Nagarpalika": 0.3,
    "Jitpur Simara Upamahanagarpalika": 0.35,
    "Jorayal Gaunpalika": 0.35,
    "Joshipur Gaunpalika": 0.35,
    "Jugal Gaunpalika": 0.3,
    "Junichande Gaunpalika": 0.35,
    "Jwalamukhi Gaunpalika": 0.35,
    "K I Singh Gaunpalika": 0.35,
    "Kabilasi Nagarpalika": 0.35,
    "Kachankawal Gaunpalika": 0.3,
    "Kageshwori Manahora Nagarpalika": 0.35,
    "Kaike Gaunpalika": 0.3,
    "Kailali, Godawari Nagarpalika": 0.35,
    "Kailari Gaunpalika": 0.3,
    "Kailash Gaunpalika": 0.35,
    "Kakani Gaunpalika": 0.35,
    "Kalaiya Upamahanagarpalika": 0.35,
    "Kaligandagi Gaunpalika": 0.35,
    "Kaligandaki Gaunpalika": 0.35,
    "Kalika Nagarpalika": 0.35,
    "Kalikamai Gaunpalika": 0.35,
    "Kalikot, Kalika Gaunpalika": 0.35,
    "Kalimati Gaunpalika": 0.4,
    "Kalinchok Gaunpalika": 0.3,
    "Kalyanpur Nagarpalika": 0.35,
    "Kamal Gaunpalika": 0.35,
    "Kamala Nagarpalika": 0.35,
    "Kamalamai Nagarpalika": 0.4,
    "Kamalbazar Nagarpalika": 0.35,
    "Kanakasundari Gaunpalika": 0.3,
    "Kanchan Gaunpalika": 0.35,
    "Kanchanpur, Mahakali Nagarpalika": 0.35,
    "Kanchanrup Nagarpalika": 0.35,
    "Kanda Gaunpalika": 0.3,
    "Kanepokhari Gaunpalika": 0.35,
    "Kankai Nagarpalika": 0.35,
    "Kanthekhola Gaunpalika": 0.35,
    "Kapilbastu Nagarpalika": 0.35,
    "Kapilbastu, Mayadevi Gaunpalika": 0.35,
    "Kapurkot Gaunpalika": 0.35,
    "Karaiyamai Gaunpalika": 0.35,
    "Karjanha Nagarpalika": 0.35,
    "Kaski, Annapurna Gaunpalika": 0.3,
    "Kaski, Madi Gaunpalika": 0.3,
    "Katahari Gaunpalika": 0.35,
    "Katahariya Nagarpalika": 0.35,
    "Katari Nagarpalika": 0.4,
    "Kathmandu Mahanagarpalika": 0.35,
    "Kaudena Gaunpalika": 0.35,
    "Kawasoti Nagarpalika": 0.4,
    "Kedarseu Gaunpalika": 0.35,
    "Kepilasagadhi Gaunpalika": 0.35,
    "Kerabari Gaunpalika": 0.35,
    "Khadadevi Gaunpalika": 0.35,
    "Khadak Nagarpalika": 0.4,
    "Khairahani Nagarpalika": 0.4,
    "Khajura Gaunpalika": 0.35,
    "Khandachakra Nagarpalika": 0.35,
    "Khandbari Nagarpalika": 0.35,
    "Khanikhola Gaunpalika": 0.35,
    "Khaniyabash Gaunpalika": 0.3,
    "Khaptadchhanna Gaunpalika": 0.35,
    "Kharpunath Gaunpalika": 0.3,
    "Khatyad Gaunpalika": 0.3,
    "Khijidemba Gaunpalika": 0.35,
    "Khotehang Gaunpalika": 0.4,
    "Khumbupasanglahmu Gaunpalika": 0.3,
    "Kirtipur Nagarpalika": 0.35,
    "Kispang Gaunpalika": 0.3,
    "Kohalpur Nagarpalika": 0.4,
    "Kolhabi Nagarpalika": 0.35,
    "Konjyosom Gaunpalika": 0.35,
    "Koshi Gaunpalika": 0.35,
    "Kotahimai Gaunpalika": 0.35,
    "Krishnanagar Nagarpalika": 0.35,
    "Krishnapur Nagarpalika": 0.35,
    "Kumakhmalika Gaunpalika": 0.35,
    "Kummayak Gaunpalika": 0.35,
    "Kuse Gaunpalika": 0.35,
    "Kushma Nagarpalika": 0.35,
    "Kwholasothar Gaunpalika": 0.3,
    "Lakshminiya Gaunpalika": 0.35,
    "Lalbandi Nagarpalika": 0.35,
    "Laligurans Nagarpalika": 0.35,
    "Lalitpur Mahanagarpalika": 0.35,
    "Lalitpur, Bagmati Gaunpalika": 0.35,
    "Lalitpur, Godawari Nagarpalika": 0.35,
    "Lalitpur, Mahalaxmi Nagarpalika": 0.35,
    "Laljhadi Gaunpalika": 0.3,
    "Lamahi Nagarpalika": 0.4,
    "Lamkichuha Nagarpalika": 0.35,
    "Laxmipur Patari Gaunpalika": 0.35,
    "Lekam Gaunpalika": 0.35,
    "Lekbeshi Nagarpalika": 0.4,
    "Letang Nagarpalika": 0.35,
    "Likhu Tamakoshi Gaunpalika": 0.35,
    "Likhupike Gaunpalika": 0.3,
    "Lisangkhu Pakhar Gaunpalika": 0.35,
    "Loharpatti Nagarpalika": 0.35,
    "Lomanthang Gaunpalika": 0.3,
    "Lumbini Sanskritik Nagarpalika": 0.35,
    "Lungri Gaunpalika": 0.35,
    "Machhapuchchhre Gaunpalika": 0.3,
    "Madane Gaunpalika": 0.35,
    "Madhav Narayan Nagarpalika": 0.3,
    "Madhuwan Nagarpalika": 0.35,
    "MadhyaNepal Nagarpalika": 0.3,
    "Madhyabindu Nagarpalika": 0.4,
    "Madhyapur Thimi Nagarpalika": 0.35,
    "Mahabharat Gaunpalika": 0.35,
    "Mahabu Gaunpalika": 0.35,
    "Mahadeva Gaunpalika": 0.35,
    "Mahagadhimai Nagarpalika": 0.35,
    "Mahakulung Gaunpalika": 0.3,
    "Mahankal Gaunpalika": 0.35,
    "Maharajgunj Nagarpalika": 0.35,
    "Mahashila Gaunpalika": 0.35,
    "Mahawai Gaunpalika": 0.35,
    "Mahottari Gaunpalika": 0.3,
    "Mai Nagarpalika": 0.35,
    "Maijogmai Gaunpalika": 0.4,
    "Maiwakhola Gaunpalika": 0.35,
    "Makalu Gaunpalika": 0.3,
    "Makawanpurgadhi Gaunpalika": 0.35,
    "Makwanpur, Bagmati Gaunpalika": 0.35,
    "Malangawa Nagarpalika": 0.35,
    "Malarani Gaunpalika": 0.35,
    "Malikaarjun Gaunpalika": 0.35,
    "Mallarani Gaunpalika": 0.35,
    "Manahari Gaunpalika": 0.35,
    "Mandandeupur Nagarpalika": 0.35,
    "Mandavi Gaunpalika": 0.35,
    "Manebhanjyang Gaunpalika": 0.35,
    "Mangala Gaunpalika": 0.3,
    "Mangalsen Nagarpalika": 0.35,
    "Mangsebung Gaunpalika": 0.4,
    "Manra Siswa Nagarpalika": 0.3,
    "Manthali Nagarpalika": 0.35,
    "Marchawari Gaunpalika": 0.35,
    "Marin Gaunpalika": 0.35,
    "Marma Gaunpalika": 0.35,
    "Marsyangdi Gaunpalika": 0.3,
    "Masta Gaunpalika": 0.35,
    "Mathagadhi Gaunpalika": 0.35,
    "Matihani Nagarpalika": 0.3,
    "Maulapur Nagarpalika": 0.35,
    "Mechinagar Nagarpalika": 0.35,
    "Meghang Gaunpalika": 0.35,
    "Melamchi Nagarpalika": 0.35,
    "Melauli Nagarpalika": 0.35,
    "Mellekh Gaunpalika": 0.35,
    "Melung Gaunpalika": 0.35,
    "Menchayam Gaunpalika": 0.35,
    "Meringden Gaunpalika": 0.3,
    "Mikwakhola Gaunpalika": 0.3,
    "Mirchaiya Nagarpalika": 0.35,
    "Mithila Bihari Nagarpalika": 0.35,
    "Mithila Nagarpalika": 0.35,
    "Modi Gaunpalika": 0.3,
    "Mohanyal Gaunpalika": 0.35,
    "Molung Gaunpalika": 0.35,
    "Morang, Miklajung Gaunpalika": 0.35,
    "Mudkechula Gaunpalika": 0.3,
    "Mugum Karmarong Gaunpalika": 0.3,
    "Mukhiyapatti Musarmiya Gaunpalika": 0.3,
    "Myagde Gaunpalika": 0.35,
    "Myagdi, Annapurna Gaunpalika": 0.3,
    "Myagdi, Malika Gaunpalika": 0.3,
    "Myanglung Nagarpalika": 0.35,
    "Nagarain Nagarpalika": 0.3,
    "Nagarjun Nagarpalika": 0.35,
    "Namkha Gaunpalika": 0.3,
    "Namobuddha Nagarpalika": 0.35,
    "Naraha Gaunpalika": 0.35,
    "Naraharinath Gaunpalika": 0.35,
    "Narainapur Gaunpalika": 0.4,
    "Narayan Nagarpalika": 0.35,
    "Narphu Gaunpalika": 0.3,
    "Nashong Gaunpalika": 0.3,
    "Naubahini Gaunpalika": 0.35,
    "Naugad Gaunpalika": 0.35,
    "Naukunda Gaunpalika": 0.3,
    "Naumule Gaunpalika": 0.35,
    "Nawadurga Gaunpalika": 0.35,
    "Nawarajpur Gaunpalika": 0.35,
    "Nechasalyan Gaunpalika": 0.35,
    "Nepalgunj Upamahanagarpalika": 0.4,
    "Neshyang Gaunpalika": 0.3,
    "Netrawati Dabjong Gaunpalika": 0.35,
    "Nijgadh Nagarpalika": 0.35,
    "Nilakantha Nagarpalika": 0.35,
    "Nisdi Gaunpalika": 0.35,
    "Nisikhola Gaunpalika": 0.35,
    "Nuwakot, Likhu Gaunpalika": 0.35,
    "Okhaldhunga, Likhu Gaunpalika": 0.35,
    "Okhaldhunga, Sunkoshi Gaunpalika": 0.35,
    "Omsatiya Gaunpalika": 0.35,
    "Pachaljharana Gaunpalika": 0.35,
    "Pacharauta Nagarpalika": 0.3,
    "Painyu Gaunpalika": 0.35,
    "Pakahamainpur Gaunpalika": 0.35,
    "Pakhribas Nagarpalika": 0.35,
    "Palata Gaunpalika": 0.35,
    "Palhi Nandan Gaunpalika": 0.35,
    "Palungtar Nagarpalika": 0.35,
    "Panauti Nagarpalika": 0.35,
    "Panchadewal Binayak Nagarpalika": 0.35,
    "Panchakanya Gaunpalika": 0.35,
    "Panchakhapan Nagarpalika": 0.35,
    "Pancheshwar Gaunpalika": 0.35,
    "Panchkhal Nagarpalika": 0.35,
    "Panchpokhari Thangpal Gaunpalika": 0.3,
    "Panchpuri Nagarpalika": 0.35,
    "Panchthar, Miklajung Gaunpalika": 0.35,
    "Pandav Gupha Gaunpalika": 0.35,
    "Panini Gaunpalika": 0.35,
    "Parashuram Nagarpalika": 0.35,
    "Parbati Kunda Gaunpalika": 0.3,
    "Paroha Nagarpalika": 0.3,
    "Parsa Gaunpalika": 0.35,
    "Parsagadhi Nagarpalika": 0.35,
    "Parwanipur Gaunpalika": 0.35,
    "Patahrishanishchare Nagarpalika": 0.35,
    "Patan Nagarpalika": 0.35,
    "Paterwasugauli Gaunpalika": 0.35,
    "Pathibhara Yangwarak Gaunpalika": 0.35,
    "Patrasi Gaunpalika": 0.3,
    "Pauwadungma Gaunpalika": 0.35,
    "Phaktanglung Gaunpalika": 0.25,
    "Phalebas Nagarpalika": 0.35,
    "Phatuwa Bijayapur Nagarpalika": 0.35,
    "Phedap Gaunpalika": 0.35,
    "Phedikhola Gaunpalika": 0.35,
    "Pheta Gaunpalika": 0.35,
    "Phidim Nagarpalika": 0.35,
    "Phikkal Gaunpalika": 0.35,
    "Phungling Nagarpalika": 0.3,
    "Pipra Gaunpalika": 0.35,
    "Pokhara Lekhnath Mahanagarpalika": 0.35,
    "Pokhariya Nagarpalika": 0.35,
    "Prasauni Gaunpalika": 0.35,
    "Pratappur Gaunpalika": 0.35,
    "Punarbas Nagarpalika": 0.3,
    "Purbakhola Gaunpalika": 0.35,
    "Purbichauki Gaunpalika": 0.35,
    "Purchaudi Nagarpalika": 0.35,
    "Putalibazar Nagarpalika": 0.35,
    "Putha Uttarganga Gaunpalika": 0.3,
    "Pyuthan Nagarpalika": 0.35,
    "Raghuganga Gaunpalika": 0.3,
    "Rainadevi Chhahara Gaunpalika": 0.35,
    "Rainas Nagarpalika": 0.3,
    "Rajapur Nagarpalika": 0.35,
    "Rajbiraj Nagarpalika": 0.35,
    "Rajdevi Nagarpalika": 0.3,
    "Rajpur Gaunpalika": 0.4,
    "Rajpur Nagarpalika": 0.3,
    "Raksirang Gaunpalika": 0.35,
    "Ramaroshan Gaunpalika": 0.35,
    "Rambha Gaunpalika": 0.35,
    "Ramdhuni Nagarpalika": 0.35,
    "Ramechhap Nagarpalika": 0.35,
    "Ramgopalpur Nagarpalika": 0.35,
    "Ramgram Nagarpalika": 0.4,
    "Ramnagar Gaunpalika": 0.3,
    "Ramprasad Rai Gaunpalika": 0.35,
    "Rampur Nagarpalika": 0.35,
    "Rangeli Nagarpalika": 0.3,
    "Rapti Gaunpalika": 0.4,
    "Rapti Nagarpalika": 0.35,
    "Rapti Sonari Gaunpalika": 0.4,
    "Raskot Nagarpalika": 0.35,
    "Rasuwa, Kalika Gaunpalika": 0.3,
    "Ratnanagar Nagarpalika": 0.4,
    "Ratuwamai Nagarpalika": 0.3,
    "Rautamai Gaunpalika": 0.4,
    "Rawa Besi Gaunpalika": 0.35,
    "Resunga Nagarpalika": 0.35,
    "Rhishing Gaunpalika": 0.35,
    "Ribdikot Gaunpalika": 0.35,
    "Rohini Gaunpalika": 0.35,
    "Rolpa Nagarpalika": 0.35,
    "Rolpa, Madi Gaunpalika": 0.35,
    "Rolpa, Tribeni Gaunpalika": 0.35,
    "Rong Gaunpalika": 0.35,
    "Roshi Gaunpalika": 0.35,
    "Rubi Valley Gaunpalika": 0.3,
    "Rukum_W, Musikot Nagarpalika": 0.35,
    "Rukum_W, Tribeni Gaunpalika": 0.35,
    "Runtigadi Gaunpalika": 0.35,
    "Rupa Gaunpalika": 0.35,
    "Rupakot Majhuwagadhi Nagarpalika": 0.35,
    "Rupandehi, Mayadevi Gaunpalika": 0.35,
    "Rupani Gaunpalika": 0.35,
    "Ruru Gaunpalika": 0.35,
    "Sabaila Nagarpalika": 0.35,
    "Sabhapokhari Gaunpalika": 0.3,
    "Sahid Lakhan Gaunpalika": 0.35,
    "Sahidnagar Nagarpalika": 0.35,
    "Sailung Gaunpalika": 0.35,
    "Sainamaina Nagarpalika": 0.35,
    "Sakela Gaunpalika": 0.35,
    "SakhuwaPrasauni Gaunpalika": 0.35,
    "Sakhuwanankarkatti Gaunpalika": 0.35,
    "Salpasilichho Gaunpalika": 0.35,
    "Salyan, Tribeni Gaunpalika": 0.35,
    "Sammarimai Gaunpalika": 0.35,
    "Samsi Gaunpalika": 0.35,
    "Sandakpur Gaunpalika": 0.35,
    "Sandhikharka Nagarpalika": 0.35,
    "Sangurigadhi Gaunpalika": 0.4,
    "Sani Bheri Gaunpalika": 0.35,
    "Sankhuwasabha, Madi Nagarpalika": 0.35,
    "Sanni Tribeni Gaunpalika": 0.35,
    "Sanphebagar Nagarpalika": 0.35,
    "Saptakoshi Nagarpalika": 0.4,
    "Saptari, Bishnupur Gaunpalika": 0.35,
    "Sarawal Gaunpalika": 0.35,
    "Sarkegad Gaunpalika": 0.3,
    "Sarumarani Gaunpalika": 0.35,
    "Satyawati Gaunpalika": 0.35,
    "Sayal Gaunpalika": 0.35,
    "Shadananda Nagarpalika": 0.35,
    "Shahidbhumi Gaunpalika": 0.4,
    "Shailyashikhar Nagarpalika": 0.35,
    "Shambhunath Nagarpalika": 0.35,
    "Shankharapur Nagarpalika": 0.35,
    "Shantinagar Gaunpalika": 0.4,
    "Sharada Nagarpalika": 0.35,
    "Shey Phoksundo Gaunpalika": 0.25,
    "Shikhar Nagarpalika": 0.35,
    "Shivanath Gaunpalika": 0.35,
    "Shivapuri Gaunpalika": 0.35,
    "Shivaraj Nagarpalika": 0.4,
    "Shivasataxi Nagarpalika": 0.35,
    "Shiwalaya Gaunpalika": 0.35,
    "Shuklagandaki Nagarpalika": 0.35,
    "Shuklaphanta Nagarpalika": 0.35,
    "Siddhalek Gaunpalika": 0.35,
    "Siddharthanagar Nagarpalika": 0.35,
    "Siddhicharan Nagarpalika": 0.35,
    "Sidingba Gaunpalika": 0.3,
    "Sigas Gaunpalika": 0.35,
    "Silichong Gaunpalika": 0.3,
    "Simkot Gaunpalika": 0.3,
    "Simraungadh Nagarpalika": 0.3,
    "Simta Gaunpalika": 0.35,
    "Sindhuli, Sunkoshi Gaunpalika": 0.35,
    "Sindhupalchowk, Sunkoshi Gaunpalika": 0.35,
    "Sinja Gaunpalika": 0.3,
    "Siraha Nagarpalika": 0.35,
    "Siraha, Bishnupur Gaunpalika": 0.35,
    "Siranchok Gaunpalika": 0.3,
    "Sirijangha Gaunpalika": 0.3,
    "Sisne Gaunpalika": 0.3,
    "Sitganga Nagarpalika": 0.4,
    "Siyari Gaunpalika": 0.35,
    "Solududhakunda Nagarpalika": 0.3,
    "Sonama Gaunpalika": 0.35,
    "Soru Gaunpalika": 0.3,
    "Sotang Gaunpalika": 0.3,
    "Suddhodhan Gaunpalika": 0.35,
    "Sudhdhodhan Gaunpalika": 0.35,
    "Sukhipur Nagarpalika": 0.35,
    "Sukidaha Gaunpalika": 0.35,
    "Sulikot Gaunpalika": 0.3,
    "Sunapati Gaunpalika": 0.35,
    "Sunchhahari Gaunpalika": 0.35,
    "Sundarbazar Nagarpalika": 0.3,
    "Sundarharaicha Nagarpalika": 0.35,
    "Sunwal Nagarpalika": 0.35,
    "Sunwarshi Nagarpalika": 0.3,
    "Surma Gaunpalika": 0.35,
    "Surnaya Gaunpalika": 0.35,
    "Surunga Nagarpalika": 0.4,
    "Suryabinayak Nagarpalika": 0.35,
    "Suryagadhi Gaunpalika": 0.35,
    "Suryodaya Nagarpalika": 0.35,
    "Suwarna Gaunpalika": 0.35,
    "Suwarnabati Gaunpalika": 0.35,
    "Swami Kartik Gaunpalika": 0.3,
    "Sworgadwary Nagarpalika": 0.35,
    "Tadi Gaunpalika": 0.35,
    "Talkot Gaunpalika": 0.3,
    "Tamakoshi Gaunpalika": 0.35,
    "Taman Khola Gaunpalika": 0.3,
    "Tanjakot Gaunpalika": 0.3,
    "Tansen Nagarpalika": 0.35,
    "Tapli Gaunpalika": 0.35,
    "Tara Khola Gaunpalika": 0.35,
    "Tarakeshwor Nagarpalika": 0.35,
    "Tarkeshwar Gaunpalika": 0.35,
    "Tatopani Gaunpalika": 0.3,
    "Temal Gaunpalika": 0.35,
    "Thaha Nagarpalika": 0.35,
    "Thakre Gaunpalika": 0.35,
    "Thakurbaba Nagarpalika": 0.35,
    "Thalara Gaunpalika": 0.35,
    "Thantikandh Gaunpalika": 0.35,
    "Thasang Gaunpalika": 0.3,
    "Thawang Gaunpalika": 0.35,
    "Thori Gaunpalika": 0.4,
    "Thuli Bheri Nagarpalika": 0.3,
    "Thulung Dudhkoshi Gaunpalika": 0.35,
    "Tikapur Nagarpalika": 0.35,
    "Tila Gaunpalika": 0.35,
    "Tilagufa Nagarpalika": 0.35,
    "Tilathi Koiladi Gaunpalika": 0.35,
    "Tillotama Nagarpalika": 0.35,
    "Tinau Gaunpalika": 0.35,
    "Tinpatan Gaunpalika": 0.35,
    "Tirahut Gaunpalika": 0.35,
    "Tokha Nagarpalika": 0.35,
    "Tribeni Nagarpalika": 0.35,
    "Tribeni Nalagad Nagarpalika": 0.3,
    "TribeniSusta Gaunpalika": 0.35,
    "Tripura Sundari Gaunpalika": 0.35,
    "Tripurasundari Gaunpalika": 0.3,
    "Tripurasundari Nagarpalika": 0.3,
    "Triyuga Nagarpalika": 0.4,
    "Tulsipur Upamahanagarpalika": 0.4,
    "Tumbewa Gaunpalika": 0.35,
    "Turmakhad Gaunpalika": 0.35,
    "Tyamkemaiyung Gaunpalika": 0.35,
    "Udayapur, Sunkoshi Gaunpalika": 0.35,
    "Udayapurgadhi Gaunpalika": 0.4,
    "Umakunda Gaunpalika": 0.3,
    "Uralabari Nagarpalika": 0.35,
    "Uttargaya Gaunpalika": 0.3,
    "Waling Nagarpalika": 0.35,
    "Yangwarak Gaunpalika": 0.35,
    "Yashodhara Gaunpalika": 0.35,
    "Yemunamai Gaunpalika": 0.3,
}

# ── Importance Factors (Table 4-4) ────────────────────────────────────────────
IMPORTANCE_FACTORS: dict[str, float] = {
    # Class I – Ordinary (those not falling in classes II and III)
    "Residential Building": 1.0,
    "Apartments": 1.0,
    "Offices": 1.0,
    "Banks / Financial Institutions": 1.0,
    "Commercial Buildings": 1.0,
    "Hospitality Buildings": 1.0,
    "Factory Buildings (<500 occupancy)": 1.0,
    # Class II
    "Schools": 1.25,
    "Colleges": 1.25,
    "Cinemas": 1.25,
    "Assembly Buildings": 1.25,
    "Shopping Malls": 1.25,
    "Convention Halls": 1.25,
    "Temples": 1.25,
    "Monumental Structures": 1.25,
    "Police Stations": 1.25,
    "Emergency Vehicle shelters/garages": 1.25,
    "Stadiums": 1.25,
    "Airport Terminals": 1.25,
    "Food Storage Structures": 1.25,
    "Emergency relief stores": 1.25,
    "Water works and water towers": 1.25,
    "Radio and Television facilities": 1.25,
    "Telephone exchanges and transmission": 1.25,
    "Offices and residential quarters for services": 1.25,
    "Buildings designed for >500 persons": 1.25,
    # Class III
    "Hospitals": 1.5,
    "Fire Stations": 1.5,
    "Police Headquarters": 1.5,
    "Air Traffic Control": 1.5,
    "Power Stations (including standby power)": 1.5,
    "Distribution facilities for gas or petroleum": 1.5,
    "Structures for support or containment of hazardous materials": 1.5,
}

# ── Soil Parameters – NBC 105:2025 Table 4-1 ─────────────────────────────────
# NOTE: The 'K' (shear-stiffness) parameter is REMOVED in the 2025 revision.
# For the Equivalent Static Method, Ta is taken as 0 (§ 4.1.2 note 1).
SOIL_PARAMS: dict[str, dict] = {
    "A": {"Ta_table": 0.1, "Tc": 0.5,  "Td": 4.0, "alpha": 2.50,
          "description": "Rock or rock-like geological formation (Vs,30 > 800 m/s)"},
    "B": {"Ta_table": 0.1, "Tc": 0.7,  "Td": 4.0, "alpha": 2.50,
          "description": "Very dense sand/gravel or very stiff clay (350 < Vs,30 ≤ 800 m/s)"},
    "C": {"Ta_table": 0.1, "Tc": 1.0,  "Td": 4.0, "alpha": 2.50,
          "description": "Dense/medium-dense sand, gravel or stiff clay (150 < Vs,30 ≤ 350 m/s)"},
    "D": {"Ta_table": 0.5, "Tc": 2.0,  "Td": 5.0, "alpha": 2.25,
          "description": "Loose-to-medium cohesionless or soft-to-firm cohesive soil (Vs,30 ≤ 150 m/s)"},
}

# ── Empirical Period Coefficients (§ 5.1.2 + § 5.1.3) ────────────────────────
# T_approx = kt * H^(3/4);  T_design = 1.25 * T_approx  (amplification per § 5.1.3)
# Fixed 2025 correction: Eccentrically Braced STEEL Frame → 0.075 (not 0.085).
# 0.085 applies ONLY to Moment Resisting STEEL frame.
KT_VALUES: dict[str, float] = {
    "For Moment Resisting Concrete Frame":          0.075,
    "For Moment Resisting Steel Frame":             0.085,
    "For Eccentrically Braced Structural Steel Frame": 0.075,   # corrected 2025
    "For all other structural system":              0.050,
}

# Amplification factor for empirical period (§ 5.1.3)
PERIOD_AMPLIFICATION_FACTOR: float = 1.25

# ── Accidental Eccentricity (§ 5.6) ──────────────────────────────────────────
# Reduced from ±0.10b (2020) to ±0.05b (2025)
ACCIDENTAL_ECCENTRICITY: float = 0.05

# ── Deflection Scale Factors – Table 6-1 ─────────────────────────────────────
# Applied to ULS deflections obtained from ESM to get more rational values.
DEFLECTION_SCALE_FACTORS_KD: dict[int, float] = {
    1: 1.00,
    2: 0.97,
    3: 0.94,
    4: 0.91,
    5: 0.88,
    6: 0.85,   # "6 or more" → conservative use of 0.85
}

# ── Seismic Weight Live-Load Fractions – Table 5-1 ───────────────────────────
SEISMIC_LIVE_LOAD_FACTORS: dict[str, float] = {
    "Storage buildings (including warehouses)": 0.60,
    "All other occupancies":                    0.30,
    "Roof areas (all buildings)":               0.00,
}

# ── Kathmandu-Valley Soil-Type-D Wards (Table 4-3) ───────────────────────────
# Municipalities whose listed ward numbers are classified as Soil Type D by
# default unless Vs,30 testing proves otherwise.
# "All" = all wards; list = specific wards only.
KTM_VALLEY_SOIL_D: dict[str, object] = {
    "Budhanilkantha Municipality":    "All",
    "Chandragiri Municipality":       "All",
    "Gokarneswor Municipality":       "All",
    "Kageswori Manahara Municipality": [8, 9],
    "Kathmandu Metropolitan City":    [1,2,5,9,10,11,12,13,14,15,16,17,18,19,
                                        20,21,22,23,24,25,26,27,28,29,30,32],
    "Kirtipur Municipality":          [10],
    "Nagarjun Municipality":          [2,4,9],
    "Sankharapur Municipality":       "All",
    "Tarakeswor Municipality":        [4,8,9,10,11],
    "Tokha Municipality":             [4,5,6,7,8,9,10,11],
    "Bagmati Rural Municipality":     "All",
    "Dakshinkali Municipality":       "All",
    "Godawari Municipality":          "All",
    "Konjyosom Rural Municipality":   "All",
    "Lalitpur Metropolitan City":     [1,2,3,4,6,7,8,9,10,11,12,13,16,17,19,20],
    "Mahalaxmi Municipality":         [1,2,3,4,5,7],
    "Mahankal Rural Municipality":    "All",
    "Bhaktapur Municipality":         "All",
    "Changunarayan Municipality":     [2],
    "Madhyapur Thimi Municipality":   "All",
    "Suryabinayak Municipality":      [2,3,5,6],
}
